# Bandit Level 21 → 22

## Objective
Find the password generated by a cron job.

## Tools Used
- `cat`, `ls /etc/cron.d/`

## Process
1. Checked cron jobs: `ls /etc/cron.d/`
2. Read the script: `cat /usr/bin/cronjob_bandit22.sh`
3. Found the target file path in the script and read it.

## What I Learned
- Investigating scheduled tasks and script automation.
